### ISSUE TITLE
Problems importing WCA export

### ISSUE THREAD

**Issue by jpbulman** [cubingusa/org#204] opened 2019-01-31 02:46 UTC
I've been trying to get the WCA export running, and I've run into an interesting problem.

`
INFO     2019-01-31 02:32:16,497 module.py:861] admin: "POST /_ah/queue/deferred HTTP/1.1" 500 10289

WARNING  2019-01-31 02:32:16,497 taskqueue_stub.py:2149] Task task29 failed to execute. This task will retry in 0.100 seconds

INFO     2019-01-31 02:32:16,736 module.py:861] admin: "POST /_ah/queue/deferred HTTP/1.1" 500 10321

WARNING  2019-01-31 02:32:16,737 taskqueue_stub.py:2149] Task task29 failed to execute. This task will retry in 0.200 seconds

INFO     2019-01-31 02:32:17,041 module.py:861] admin: "POST /_ah/queue/deferred HTTP/1.1" 500 10321

WARNING  2019-01-31 02:32:17,042 taskqueue_stub.py:2149] Task task29 failed to execute. This task will retry in 0.400 seconds

INFO     2019-01-31 02:32:17,564 module.py:861] admin: "POST /_ah/queue/deferred HTTP/1.1" 500 10321

WARNING  2019-01-31 02:32:17,565 taskqueue_stub.py:2149] Task task29 failed to execute. This task will retry in 0.800 seconds

INFO     2019-01-31 02:32:18,471 module.py:861] admin: "POST /_ah/queue/deferred HTTP/1.1" 500
`
The task time just keeps doubling, I eventually ran out of swap because I left it idle for too long. It seems like this is being caused by the POST request getting a 500 back. I'm not really sure how to avoid this, any ideas?

EDIT: Do I need to do anything with the admin [yaml](https://github.com/cubingusa/org/blob/b9856a44d7bd5f619a11ccf2ef956c252a94852c/admin.yaml)? Or is this something with google app engine?

**Comment by jpbulman** [comment] 2019-05-24 16:40
If anyone has an idea on how to go about fixing this, that would be appreciated

**Comment by jpbulman** [comment] 2019-08-12 20:10
Now that nationals is over, does anyone think they can give me a hand with solving this problem? @cubingusa/software

**Comment by FatBoyXPC** [comment] 2019-08-12 20:12
Unfortunately I'm not super familiar with the python framework that's being used. Maybe @timreyn could help? I can also bug @jfly about it since he's a python guru.

**Comment by jfly** [comment] 2019-08-12 20:15
Could you give some more information about how to reproduce this issue, @jpbulman? Are you running the code locally? In prod? In your own google app engine instance?

**Comment by timreyn** [comment] 2019-08-13 00:22
Hmm, it's unfortunately not giving any useful errors :/

It's also surprising that it got all the way through most of the tables before it raised that error.  RanksSingle is pretty late on the list: https://github.com/cubingusa/org/blob/568b4b41a09aecdadbff93914ea6e41b62564cb5/src/wca/export.py#L129

Can you confirm that other tables were imported successfully by going to localhost:8000 and looking at the datastore viewer?

**Comment by timreyn** [comment] 2019-08-13 00:27
If you're running the site with dev_app.sh, that should run the right files, and should make sure the deferred handler is set up.

Can you add a print statement here: https://github.com/cubingusa/org/blob/568b4b41a09aecdadbff93914ea6e41b62564cb5/src/wca/export.py#L33 and see if the control flow is getting into the function that processes the export?

**Comment by jpbulman** [comment] 2019-08-13 01:27
@jfly I'm currently running [these](https://github.com/cubingusa/org/blob/master/doc/deploy_new.md) steps locally on my machine, more specifically #6 in that list.

@timreyn When I go into the datastore viewer it looks like I have AppSetting, Person, RankSingle, Region, State, and User. I just added a print statement and am going to try and run it again, I'll bump this with how it goes.

Thanks for the help everyone!

**Comment by timreyn** [comment] 2022-02-24 13:01
I rewrote the DB import as part of #240 and it is substantially simpler now.  Closing this as obsolete.

**Closed as completed by timreyn** 2022-02-24 13:01 UTC
